### ISSUE TITLE
Adopt Stimulus (lightweight JS framework)

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/roadmap#21]
## Summary

We are adopting Stimulus as the lightweight JavaScript framework in Wagtail to replace the need for jQuery, inline scripts and excessive global usage for per-component usage data.

## Intended Outcome

Parts of Wagtail’s existing jQuery code and inline scripts have been replaced with Stimulus controllers, and we have a clear direction on how to do lightweight interactivity in the future.

## How will it work?

Stimulus will be integrated into Wagtail and leveraged by existing core components. Documentation will be available for core contributors, as well as APIs for third-party customisations.

## More information

- See [RFC 78: Adopt Stimulus (lightweight JS framework) 🎛️](https://github.com/wagtail/rfcs/pull/78)

**Comment by lb-** [comment]
Yay

**Comment by thibaudcolas** [comment]
[Wagtail 4.2 release notes: CSP compatibility & Stimulus adoption](https://docs.wagtail.org/en/stable/releases/4.2.html#csp-compatibility-stimulus-adoption)
