### ISSUE TITLE
Multiple chooser UI for InlinePanels

### ISSUE THREAD

**Issue by gasman** [wagtail/roadmap#29]
## Summary

A common pattern in page models is a chooser widget within an InlinePanel - for example, to implement an image gallery, a "related pages" sidebar, or associating a page with multiple categories as defined by snippets. In these cases it's tedious to repeatedly insert a new child form and open the chooser for each item to be added - we wish to provide an improved UI component where multiple items can be selected and added at once.

## Intended Outcome

A new MultipleChooserPanel is available in `wagtail.admin.panels`, following the behaviour and API of InlinePanel but with the "Add new" button opening a model that allows selecting multiple items at once, which then appear as the appropriate set of child forms.

## More information

- See https://github.com/wagtail/wagtail/issues/2203.

**Comment by thibaudcolas** [comment]
It happened! See [v4.2 release notes: Multiple chooser panel](https://docs.wagtail.org/en/stable/releases/4.2.html#multiple-chooser-panel).
