### ISSUE TITLE
Universal listings

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/roadmap#33]
## Summary

Exploring design solutions for making sites / sections with 1000s of pages and little to no tree structure easier to navigate in the CMS.

The aim is to enhance the searching / filtering capabilities of the main page listing view (and to eventually roll out the same patterns and functionality to all listings within the CMS).

## Intended Outcome

Websites / sections of websites with thousands of pages and little to no structure are easier to navigate in the CMS. Other websites are also easier to manage.

## More information

- [Universal listings (search and filtering) #10446](https://github.com/wagtail/wagtail/discussions/10446)
- [RFC 82: Treeless page listings](https://github.com/wagtail/rfcs/pull/82)

**Comment by nrezvoi** [comment]
Much needed functionality, I have multi-site setup with 20+ languages and tons of content types, using current page tree is a nightmare, ModelAdmin package saves some nerves, but it's not ideal and is going to be deprecated in future releases

**Comment by thibaudcolas** [comment]
This is now moving to the next release. If anyone wants to keep up with the latest work on this, the best place is still [Universal listings (search and filtering) #10446](https://github.com/wagtail/wagtail/discussions/10446).

**Comment by thibaudcolas** [comment]
Closing now to reflect the progress made in v5.2, with a follow-up at #62. A lot of progress has been made, particularly on the designs, and there is more to do to complete the implementation.

See [Universal listings (search and filtering) #10446](https://github.com/wagtail/wagtail/discussions/10446#discussioncomment-7302866) in GitHub Discussions for the latest update on progress, and [static-wagtail-v5-2](https://static-wagtail-v5-2.netlify.app/admin/pages/60/) for a static demo.
