### ISSUE TITLE
Accessibility checker enhancements

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/roadmap#36]
## Summary

Follow-up to Wagtail 4.2’s [new accessibility checker](https://wagtail.org/blog/introducing-wagtails-new-accessibility-checker/).

## Intended Outcome

Proposed additions:

- [Sorting accessibility checker results based on their order on the page #10013](https://github.com/wagtail/wagtail/issues/10013)
- [Highlight elements with errors in accessibility checker (outline) #10138](https://github.com/wagtail/wagtail/issues/10138)
- [Support custom configuration options in accessibility checker #10137](https://github.com/wagtail/wagtail/issues/10137)
- [Keyboard support improvements in accessibility checker #10135](https://github.com/wagtail/wagtail/issues/10135)
- (Stretch) [Integrate accessibility checker within the page editor #10136](https://github.com/wagtail/wagtail/issues/10136)

## More information

- See discussion: [Built-in accessibility checker for Wagtail #9262](https://github.com/wagtail/wagtail/discussions/9262).

**Comment by lb-** [comment]
Might be nice to also ensure this feature is documented in Wagtail documentation (enable/disable/configure) and also the guide. 

I've added an issue for the guide https://github.com/wagtail/guide/issues/303

**Comment by thibaudcolas** [comment]
@lb- the checker is currently documented here: https://docs.wagtail.org/en/stable/advanced_topics/accessibility_considerations.html#built-in-accessibility-checker

Current configuration is currently only whether the checker is part of the userbar items or not, so we’ve directly referred to the [`construct_wagtail_userbar` hook documentation](https://docs.wagtail.org/en/stable/reference/hooks.html#construct-wagtail-userbar) in the release notes.

It would be nice to document this for end users eventually but I don’t think this will be a priority any time soon as we’re still planning quite big changes to how the checker works.

**Comment by lb-** [comment]
Thanks Thibaud - my apologies I must have missed that.

**Comment by thibaudcolas** [comment]
Closing this as _Done_ in v5.0 (release candidate due soon). There are two points from the above list that didn’t happen:

> - [Keyboard support improvements in accessibility checker #10135](https://github.com/wagtail/wagtail/issues/10135)
> - (Stretch) [Integrate accessibility checker within the page editor #10136](https://github.com/wagtail/wagtail/issues/10136)

Will try to schedule those for a future release (TBC)
