### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/roadmap#42]
Follow-up to earlier consolidation of search functionality.

## Intended Outcome

- Implement missing features in db search backends: boosting / limiting fields
- Pick a successor to elasticsearch as our best-of-breed search backend
- Move search into separate package
- New search back-end
- Better docs/APIs for third-parties

**Comment by olifante** [comment]
ParadeDb just announced their `pg_bm25` Posgres extension, providing Elastic-search-like capabilities inside Postgres. Could be interesting to investigate the feasibility of adopting it for rich Wagtail search.

```pg_bm25: Elastic-Quality Full Text Search Inside Postgres
[...]
We’re unveiling pg_bm25: a Rust-based Postgres extension that significantly improves Postgres’ full text search capabilities. pg_bm25 is named after BM25, the algorithm used by modern search engines to calculate the relevance scores of search results.
[...]
pg_bm25 aims to bridge the gap between the native capabilities of Postgres’ full text search and those of a specialized search engine like ElasticSearch. The goal is to eliminate the need to bring a cumbersome service like ElasticSearch into the data stack.
```

https://docs.paradedb.com/blog/introducing_bm25

**Comment by thibaudcolas** [comment]
For search improvements shipping in v5.2, see [Wagtail 5.2 (LTS) release notes](https://docs.wagtail.org/en/stable/releases/5.2.html#wagtail-5-2-lts-release-notes)
