### ISSUE TITLE
Image optimisations

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/roadmap#44]
## Summary

Improvements to reduce the weight of images generated with Wagtail, that will be relevant for all sites with little to no rework.

## Intended outcome

- [ ] [RFC 71: support for responsive images](https://github.com/wagtail/rfcs/blob/main/text/071-responsive-images-support.md)
- [x] Lossless and lossy [image optimisation operations (Willow#69)](https://github.com/wagtail/Willow/pull/69)
- [x] [AVIF support #10486](https://github.com/wagtail/wagtail/issues/10486)

**Comment by lb-** [comment]
Added media & performance tags.

**Comment by thibaudcolas** [comment]
See [Responsive & multi-format images with the picture tag](https://docs.wagtail.org/en/stable/releases/5.2.html#responsive-multi-format-images-with-the-picture-tag) in v5.2 release notes, and [AVIF image support](https://docs.wagtail.org/en/stable/releases/5.1.html#avif-image-support) in v5.1 release notes.
