### ISSUE TITLE
CSP compatibility improvements

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/roadmap#61]
Follow-up to [Extend Stimulus adoption #57](https://github.com/wagtail/roadmap/issues/57). Further adoption of Stimulus to support stricter CSP policies (stop using inline JS to initialise features).

Exact improvements TBC in line with [Stimulus adoption planning](https://github.com/orgs/wagtail/projects/14/views/1).

**Comment by lb-** [comment]
Update as at the 5.1 release (August 2023). See previous update comment: https://github.com/wagtail/roadmap/issues/57#issuecomment-1579390531

## Currently implemented

We have [18 controllers implemented](https://github.com/wagtail/wagtail/blob/main/client/src/controllers/index.ts), 6 of which were added in the last release.

- `DialogController` 'w-dialog'
- `DropdownController` 'w-dropdown'
- `SwapController` 'w-swap'
- `TagController` 'w-tag'
- `TeleportController` 'w-teleport'
- `TooltipController` 'w-tooltip'

## State of inline script usage

A list of areas of code that still use inline scripts, roughly from most common to least common, roughly being used to determine next steps.

1. Date pickers (PR up)
2. Bulk actions (progress being made, no issue raised)
3. Metadata/locale/config items - in limbo, need some direction on https://github.com/wagtail/wagtail/issues/9771
4. Choosers/Workflow actions - no progress
5. InlinePanel/formset - some pre-work issues created, no progress
6. File upload / title changes
7. Dirty form check / unsaved changes - issue created
8. Initialise comments - no progress

## Pull requests

### Ready to review

- https://github.com/wagtail/wagtail/pull/10590 (documentation, has had one round of feedback, awaiting next round)
- https://github.com/wagtail/wagtail/pull/10613 (small w-bulk adoption/enhancement, making way for bulk actions)

### Blocked

- https://github.com/wagtail/wagtail/pull/10261 (awaiting team decision on direction of date pickers)
- https://github.com/wagtail/wagtail/pull/10311 (LB will refine after docs are in place)

### Inactive

- https://github.com/wagtail/wagtail/pull/10160 (LB working on this)
- https://github.com/wagtail/wagtail/pull/10238 (LB working on this)
- https://github.com/wagtail/wagtail/pull/10327 (no takers yet, LB can do later)

**Comment by thibaudcolas** [comment]
For a record of what shipped in v5.2, see:

- [Support extending Wagtail client-side with Stimulus](https://docs.wagtail.org/en/stable/releases/5.2.html#support-extending-wagtail-client-side-with-stimulus)
- [Maintenance - Stimulus adoption](https://docs.wagtail.org/en/stable/releases/5.2.html#stimulus-adoption)
